name = "SymbolicCircuit"
uuid = "90f18bad-8de6-4f24-a7ee-bfe158ef45c0"
authors = ["overshiki <le.niu@hotmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"

[compat]
MacroTools = "0.5.9"
Metatheory = "1.3.3"
julia = "1"